name: Terminate EC2 Instances

on:
    workflow_dispatch:

jobs:
    terminate-instances:
        runs-on: ubuntu-latest
        steps:
          - name: Set up AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
        
          - name: Get Instance IDs by Name
            id: get-instance-ids
            run: |
              aws ec2 describe-instances --filters "Name=tag:Name,Values=Personal Website" --query "Reservations[*].Instances[*].InstanceId" --output text | tr '\n' ' ' | sed 's/ $//' > instance_ids.txt

          - name: Terminate Instances
            if: steps.get-instance-ids.outputs != ''
            run: |
              cat instance_ids.txt | xargs -n 1 aws ec2 terminate-instances --instance-ids